# This workflow will install Python dependencies and run tests on the code snippets included in the documentation.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Documentation Script Test

on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches: [ main ]
    paths:
      - 'hover/**.py'
      - 'docs/pages/**.md'
      - 'docs/pipelines/*.py'
      - 'docs/snippets/markdown/dataset-prep.md'
      - 'docs/snippets/py/*.*'
  pull_request:
    branches: [ main ]
    paths:
      - 'hover/**.py'
      - 'docs/pages/**.md'
      - 'docs/pipelines/*.py'
      - 'docs/snippets/markdown/dataset-prep.md'
      - 'docs/snippets/py/*.*'
  workflow_dispatch:

jobs:
  doc-script:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9']
        os: [ubuntu-latest]

    steps:
    - name: Clone hover
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Non-Python Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsndfile1

    - name: Test with Tox
      run: |
        pip install --upgrade pip
        pip install --upgrade tox tox-gh-actions
        tox -e test_doc_scripts
