# This workflow will install Python dependencies and run tests on the source code.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Quick Source Test

on:
  push:
    branches: [ main, nightly ]
    paths:
      - 'hover/**.py'
      - 'tests/**.py'
      - 'pytest.ini'
      - 'fixture_module/**.py'
  pull_request:
    branches: [ main, nightly ]
    paths:
      - 'hover/**.py'
      - 'tests/**.py'
      - 'pytest.ini'
      - 'fixture_module/**.py'
  workflow_dispatch:

jobs:
  test-api:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # test oldest and newest supported Python version
        python-version: ['3.8', '3.9']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Find cached tox env
      id: find-venv
      uses: actions/cache@v2
      with:
        path: .tox
        key: ${{ runner.os }}-${{ runner.python-version }}-tox-env-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.python-version }}-tox-env-

    - name: Test and make coverage report
      run: |
        pip install --upgrade pip
        pip install --upgrade tox tox-gh-actions
        tox -e test_api

    - name: Codacy Coverage Reporter
      uses: codacy/codacy-coverage-reporter-action@master
      if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: cobertura.xml
